[feature/TestScriptDataBase_Imple] Initial implementation of TestScri…
kjw0384/SSDProject pull request #38
Opened 2024-06-07 05:32 UTC by JiwnwooHong601

TestScript DB 초기코드입니다. (TestShell과 연동 안되었고 프로젝트 세팅 + 기본 코드 만으로 단독 빌드 되고 있습니닷)

2024-06-07 05:49 UTC, dongww12 requested changes

2024-06-07 05:49 UTC, dongww12 commented on TestShellApp/TestShellApp.vcxproj
> +    <ClCompile Include="TestCaseContianer.cpp" />
아,TestCaseContainer.cpp가 포함이 안된 것 같습니다!!

2024-06-07 06:38 UTC, kjw0384 approved these changes
👍 
완성 이후에 TODO 항목만 확인해보겠습니다.

2024-06-09 23:28 UTC, kjw0384 reviewed
TestScriptDescriptor_ReadAndCompare.h
TestScriptRead.cpp
가 실질적으로 빈 파일인데, 용도가 어떻게 되나요?

2024-06-09 23:43 UTC, dongww12 approved these changes
TestScript 클래스를 정말 잘 작성해주신 것 같습니다! 수고 많으셨습니다^^

2024-06-09 23:43 UTC, dongww12 commented on TestCaseDataBase/TestScriptDataBase.cpp
> +			tscObj = new TestScript##NAME;\
진우님~ 이건 질문드리는 건데 매크로 작성할 때 #은 어떤 효과가 있는거예요?

2024-06-09 23:44 UTC, JiwnwooHong601 commented
> TestScriptDescriptor_ReadAndCompare.h TestScriptRead.cpp 가 실질적으로 빈 파일인데, 용도가 어떻게 되나요?

둘 모두 TestScript 종류 추가시에, 그에 mapping되는 인터페이스를 상속한파생클래스가 생길때 추가되는 파일입니다. 
현재는 매크로로 자동으로 클래스 구성되는 로직을 타고있어 사용하지 않는 파일입니다.  지워서 merge 하겠습니다~!

2024-06-09 23:52 UTC, JiwnwooHong601 commented on TestCaseDataBase/TestScriptDataBase.cpp
> +			tscObj = new TestScript##NAME;\
#은 매크로 매개변수로 전달된 토큰을 문자열로 구문에 전달할때 사용되는 문법입니다!

2024-06-10 00:35 UTC, merged